// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonTools.Web.Infrastructure.Db;

#nullable disable

namespace PokemonTools.Web.Infrastructure.Db.Migrations
{
    [DbContext(typeof(PokemonToolsDbContext))]
    [Migration("20260330122249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Abilities.AbilityEntity", b =>
                {
                    b.Property<int>("AbilityId")
                        .HasColumnType("integer")
                        .HasComment("特性ID PokeAPIでのid");

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("特性名 日本語名");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.HasKey("AbilityId");

                    b.ToTable("Abilities", t =>
                        {
                            t.HasComment("特性");
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualCategoryEntity", b =>
                {
                    b.Property<int>("IndividualCategoryId")
                        .HasColumnType("integer")
                        .HasComment("個体カテゴリID 連番");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<string>("IndividualCategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("個体カテゴリ名");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.HasKey("IndividualCategoryId");

                    b.ToTable("IndividualCategories", t =>
                        {
                            t.HasComment("個体カテゴリ");
                        });

                    b.HasData(
                        new
                        {
                            IndividualCategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IndividualCategoryName = "手持ち個体",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            IndividualCategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IndividualCategoryName = "ダメージ計算プリセット個体",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualEntity", b =>
                {
                    b.Property<string>("IndividualId")
                        .HasColumnType("text")
                        .HasComment("個体ID prefix_uuidv7");

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer")
                        .HasComment("特性ID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasComment("カテゴリID");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<int?>("HeldItemId")
                        .HasColumnType("integer")
                        .HasComment("持ち物 道具ID");

                    b.Property<string>("IndividualName")
                        .HasColumnType("text")
                        .HasComment("個体名 NULLだったら表示時に種族名を表示");

                    b.Property<string>("Memo")
                        .HasColumnType("text")
                        .HasComment("備考");

                    b.Property<int>("Move1Id")
                        .HasColumnType("integer")
                        .HasComment("技1ID");

                    b.Property<int?>("Move2Id")
                        .HasColumnType("integer")
                        .HasComment("技2ID");

                    b.Property<int?>("Move3Id")
                        .HasColumnType("integer")
                        .HasComment("技3ID");

                    b.Property<int?>("Move4Id")
                        .HasColumnType("integer")
                        .HasComment("技4ID");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasComment("種族ID");

                    b.Property<int>("StatAlignmentId")
                        .HasColumnType("integer")
                        .HasComment("能力補正ID");

                    b.Property<int>("StatPointAttack")
                        .HasColumnType("integer")
                        .HasComment("能力ポイント::こうげき");

                    b.Property<int>("StatPointDefense")
                        .HasColumnType("integer")
                        .HasComment("能力ポイント::ぼうぎょ");

                    b.Property<int>("StatPointHp")
                        .HasColumnType("integer")
                        .HasComment("能力ポイント::HP");

                    b.Property<int>("StatPointSpecialAttack")
                        .HasColumnType("integer")
                        .HasComment("能力ポイント::とくこう");

                    b.Property<int>("StatPointSpecialDefense")
                        .HasColumnType("integer")
                        .HasComment("能力ポイント::とくぼう");

                    b.Property<int>("StatPointSpeed")
                        .HasColumnType("integer")
                        .HasComment("能力ポイント::すばやさ");

                    b.Property<int>("TeraTypeId")
                        .HasColumnType("integer")
                        .HasComment("テラスタイプID");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.HasKey("IndividualId");

                    b.HasIndex("AbilityId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("HeldItemId");

                    b.HasIndex("Move1Id");

                    b.HasIndex("Move2Id");

                    b.HasIndex("Move3Id");

                    b.HasIndex("Move4Id");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("StatAlignmentId");

                    b.HasIndex("TeraTypeId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Individuals", t =>
                        {
                            t.HasComment("個体（育成済ポケモン）");
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Items.ItemEntity", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasComment("道具ID PokeAPIでのid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<int?>("FlingPower")
                        .HasColumnType("integer")
                        .HasComment("投げつけるの威力 投げつけるが失敗する道具はNULL");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("道具名 日本語名");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.HasKey("ItemId");

                    b.ToTable("Items", t =>
                        {
                            t.HasComment("道具");
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Moves.MoveDamageClassEntity", b =>
                {
                    b.Property<int>("MoveDamageClassId")
                        .HasColumnType("integer")
                        .HasComment("技分類ID PokeAPIでのid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<string>("MoveDamageClassName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("技分類名 日本語名");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.HasKey("MoveDamageClassId");

                    b.ToTable("MoveDamageClasses", t =>
                        {
                            t.HasComment("技分類");
                        });

                    b.HasData(
                        new
                        {
                            MoveDamageClassId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MoveDamageClassName = "へんか",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            MoveDamageClassId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MoveDamageClassName = "ぶつり",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            MoveDamageClassId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MoveDamageClassName = "とくしゅ",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Moves.MoveEntity", b =>
                {
                    b.Property<int>("MoveId")
                        .HasColumnType("integer")
                        .HasComment("技ID PokeAPIでのid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<int>("MoveDamageClassId")
                        .HasColumnType("integer")
                        .HasComment("技分類ID");

                    b.Property<string>("MoveName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("技名 日本語名");

                    b.Property<int?>("Power")
                        .HasColumnType("integer")
                        .HasComment("威力");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasComment("タイプID");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.HasKey("MoveId");

                    b.HasIndex("MoveDamageClassId");

                    b.HasIndex("TypeId");

                    b.ToTable("Moves", t =>
                        {
                            t.HasComment("技");
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Parties.PartyEntity", b =>
                {
                    b.Property<string>("PartyId")
                        .HasColumnType("text")
                        .HasComment("パーティID prefix_uuidv7");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<string>("Individual1Id")
                        .HasColumnType("text")
                        .HasComment("個体1ID");

                    b.Property<string>("Individual2Id")
                        .HasColumnType("text")
                        .HasComment("個体2ID");

                    b.Property<string>("Individual3Id")
                        .HasColumnType("text")
                        .HasComment("個体3ID");

                    b.Property<string>("Individual4Id")
                        .HasColumnType("text")
                        .HasComment("個体4ID");

                    b.Property<string>("Individual5Id")
                        .HasColumnType("text")
                        .HasComment("個体5ID");

                    b.Property<string>("Individual6Id")
                        .HasColumnType("text")
                        .HasComment("個体6ID");

                    b.Property<string>("Memo")
                        .HasColumnType("text")
                        .HasComment("備考");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("パーティ名");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.HasKey("PartyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Individual1Id");

                    b.HasIndex("Individual2Id");

                    b.HasIndex("Individual3Id");

                    b.HasIndex("Individual4Id");

                    b.HasIndex("Individual5Id");

                    b.HasIndex("Individual6Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Parties", t =>
                        {
                            t.HasComment("パーティ");
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Species.SpeciesEntity", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasComment("種族ID PokeAPIでのpokemonエンドポイントのid");

                    b.Property<int>("Ability1Id")
                        .HasColumnType("integer")
                        .HasComment("特性1ID");

                    b.Property<int?>("Ability2Id")
                        .HasColumnType("integer")
                        .HasComment("特性2ID");

                    b.Property<int>("BaseStatAttack")
                        .HasColumnType("integer")
                        .HasComment("種族値::こうげき");

                    b.Property<int>("BaseStatDefense")
                        .HasColumnType("integer")
                        .HasComment("種族値::ぼうぎょ");

                    b.Property<int>("BaseStatHp")
                        .HasColumnType("integer")
                        .HasComment("種族値::HP");

                    b.Property<int>("BaseStatSpecialAttack")
                        .HasColumnType("integer")
                        .HasComment("種族値::とくこう");

                    b.Property<int>("BaseStatSpecialDefense")
                        .HasColumnType("integer")
                        .HasComment("種族値::とくぼう");

                    b.Property<int>("BaseStatSpeed")
                        .HasColumnType("integer")
                        .HasComment("種族値::すばやさ");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<int?>("HiddenAbilityId")
                        .HasColumnType("integer")
                        .HasComment("隠れ特性ID");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("種族名 日本語名");

                    b.Property<int>("Type1Id")
                        .HasColumnType("integer")
                        .HasComment("タイプ1ID");

                    b.Property<int?>("Type2Id")
                        .HasColumnType("integer")
                        .HasComment("タイプ2ID");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasComment("体重 PokeAPIでの値そのまま");

                    b.HasKey("SpeciesId");

                    b.HasIndex("Ability1Id");

                    b.HasIndex("Ability2Id");

                    b.HasIndex("HiddenAbilityId");

                    b.HasIndex("Type1Id");

                    b.HasIndex("Type2Id");

                    b.ToTable("Species", t =>
                        {
                            t.HasComment("ポケモンの種族");
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.StatAlignments.StatAlignmentEntity", b =>
                {
                    b.Property<int>("StatAlignmentId")
                        .HasColumnType("integer")
                        .HasComment("能力補正ID PokeAPIでのid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<string>("StatAlignmentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("能力補正名 日本語名");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.HasKey("StatAlignmentId");

                    b.ToTable("StatAlignments", t =>
                        {
                            t.HasComment("能力補正");
                        });

                    b.HasData(
                        new
                        {
                            StatAlignmentId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "がんばりや",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "ずぶとい",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "ひかえめ",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "おだやか",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "おくびょう",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "さみしがり",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "すなお",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "おっとり",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "おとなしい",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "せっかち",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "いじっぱり",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "わんぱく",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "てれや",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "しんちょう",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "うっかりや",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "ようき",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "やんちゃ",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "のうてんき",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "きまぐれ",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "むじゃき",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 21,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "ゆうかん",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "のんき",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 23,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "れいせい",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 24,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "なまいき",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            StatAlignmentId = 25,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StatAlignmentName = "まじめ",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Types.TypeEntity", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasComment("タイプID PokeAPIでのid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("作成日時");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("タイプ名 日本語名");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新日時");

                    b.HasKey("TypeId");

                    b.ToTable("Types", t =>
                        {
                            t.HasComment("ポケモンのタイプ");
                        });

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "ノーマル",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "かくとう",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "ひこう",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "どく",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "じめん",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "いわ",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "むし",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "ゴースト",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "はがね",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "ほのお",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "みず",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "くさ",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "でんき",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "エスパー",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "こおり",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "ドラゴン",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "あく",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "フェアリー",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "ステラ",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TypeId = 10001,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TypeName = "???",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualEntity", b =>
                {
                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Abilities.AbilityEntity", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Items.ItemEntity", "HeldItem")
                        .WithMany()
                        .HasForeignKey("HeldItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Moves.MoveEntity", "Move1")
                        .WithMany()
                        .HasForeignKey("Move1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Moves.MoveEntity", "Move2")
                        .WithMany()
                        .HasForeignKey("Move2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Moves.MoveEntity", "Move3")
                        .WithMany()
                        .HasForeignKey("Move3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Moves.MoveEntity", "Move4")
                        .WithMany()
                        .HasForeignKey("Move4Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Species.SpeciesEntity", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.StatAlignments.StatAlignmentEntity", "StatAlignment")
                        .WithMany()
                        .HasForeignKey("StatAlignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Types.TypeEntity", "TeraType")
                        .WithMany()
                        .HasForeignKey("TeraTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Category");

                    b.Navigation("HeldItem");

                    b.Navigation("Move1");

                    b.Navigation("Move2");

                    b.Navigation("Move3");

                    b.Navigation("Move4");

                    b.Navigation("Species");

                    b.Navigation("StatAlignment");

                    b.Navigation("TeraType");
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Moves.MoveEntity", b =>
                {
                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Moves.MoveDamageClassEntity", "MoveDamageClass")
                        .WithMany()
                        .HasForeignKey("MoveDamageClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Types.TypeEntity", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MoveDamageClass");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Parties.PartyEntity", b =>
                {
                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualEntity", "Individual1")
                        .WithMany()
                        .HasForeignKey("Individual1Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualEntity", "Individual2")
                        .WithMany()
                        .HasForeignKey("Individual2Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualEntity", "Individual3")
                        .WithMany()
                        .HasForeignKey("Individual3Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualEntity", "Individual4")
                        .WithMany()
                        .HasForeignKey("Individual4Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualEntity", "Individual5")
                        .WithMany()
                        .HasForeignKey("Individual5Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Individuals.IndividualEntity", "Individual6")
                        .WithMany()
                        .HasForeignKey("Individual6Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Individual1");

                    b.Navigation("Individual2");

                    b.Navigation("Individual3");

                    b.Navigation("Individual4");

                    b.Navigation("Individual5");

                    b.Navigation("Individual6");
                });

            modelBuilder.Entity("PokemonTools.Web.Infrastructure.Db.Species.SpeciesEntity", b =>
                {
                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Abilities.AbilityEntity", "Ability1")
                        .WithMany()
                        .HasForeignKey("Ability1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Abilities.AbilityEntity", "Ability2")
                        .WithMany()
                        .HasForeignKey("Ability2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Abilities.AbilityEntity", "HiddenAbility")
                        .WithMany()
                        .HasForeignKey("HiddenAbilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Types.TypeEntity", "Type1")
                        .WithMany()
                        .HasForeignKey("Type1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTools.Web.Infrastructure.Db.Types.TypeEntity", "Type2")
                        .WithMany()
                        .HasForeignKey("Type2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ability1");

                    b.Navigation("Ability2");

                    b.Navigation("HiddenAbility");

                    b.Navigation("Type1");

                    b.Navigation("Type2");
                });
#pragma warning restore 612, 618
        }
    }
}
